# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Contacto' do
  	use_frameworks!
	
	pod 'SwiftyJSON'
	pod 'ObjectMapper', '~> 1.3'
	pod 'SCLAlertView'
  	target 'ContactoTests' do
    	inherit! :search_paths
    	# Pods for testing
  	end

  	target 'ContactoUITests' do
    	inherit! :search_paths
    	# Pods for testing
  	end
end
